apiVersion: v1
kind: Service
metadata:
  name: ingress-lb
  namespace: kube-system
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
    - port: 443
      protocol: TCP
      targetPort: 443
      name: https
  selector:
    app.kubernetes.io/name: nginx-ingress-controller
  type: LoadBalancer
