apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 50000
      protocol: TCP
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/name: jenkins
  type: ClusterIP