apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-keycloak-psql
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 15Gi
  hostPath:
    path: /data/keycloak-psql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-keycloak-psql
spec:
  volumeName: pv-keycloak-psql
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
