persistence:
  enabled: true
  storageClass: standard
  size: 10Gi
serviceAccount:
  master:
    name: jenkins
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - build.simonjamesrowe.com
  paths:
    - "/"
  tls:
    - hosts:
        - build.simonjamesrowe.com
      secretName: wildcard-cert
referenceContent:
  - data:
      - fileName: plugins.txt
        fileContent: |
          configuration-as-code
          configuration-as-code-support
          workflow-aggregator
          kubernetes
          kubernetes-credentials-provider
          job-dsl
