keycloak:
  username: admin
  existingSecret: keycloak
  existingSecretKey: password
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - auth.simonjamesrowe.com
  persistence:
    deployPostgres: true
    dbVendor: postgres
    existingSecret: keycloak
    existingSecretKey: db-password

postgresql:
  persistence:
    enabled: true
    storageClass: keycloak-postgress
    size: 8Gi
